#1 List the number of films per category.
USE sakila;

SELECT category_id, COUNT(film_id)
FROM film
INNER JOIN film_category
USING (film_id)
GROUP BY category_id;


#2 Retrieve the store ID, city, and country for each store.
SELECT s.store_ID, ci.city, co.country
FROM store AS s
JOIN address AS a 
ON s.address_id = a.address_id
JOIN city as ci 
ON a.city_id = ci.city_id
JOIN country AS co 
ON ci.country_id = co.country_id;

#3 Calculate the total revenue generated by each store in dollars.
SELECT sum(p.amount), s.store_id
FROM payment as p
JOIN staff as s 
USING (staff_id)
GROUP BY store_id;


#4 Determine the average running time of films for each category.
SELECT category_id, AVG(LENGTH)
FROM film_category as fc
JOIN film as f
USING (film_id)
GROUP BY category_id;



